namespace LMS.Core.Enums
{
    public enum TableNames
    {
        attachments,
        permissions,
        feature,
        enums,
        enumline,
        course,
        UserTargets,
        City, client,
        Schedule,
        sch, ScheduleDayEvent,
        notification_log, notificationtemplate,
        schLine,
        attendance, scheduleday,
        CityStudent,usertask,
        vocabulary,
        patient,
        Student,
        useraccount,
        ScheduleDaysEvents,
        user,
        coursedetail,
        courseschedule,
        Inquiry,
        classtiming,
        topic,
        lecture,
        assignTask,
        student,
        task,
        Tasks,
        taskcomment,
        assignclass,
        branchschool,
        fee,
        feeline,
        feetypeschool,
        guardianschool,
        studentschool,
        school,
        teacher,
        page,
        PatientLabTest,
        SampleType,
        lAB_Specimen,
        patientlabtest,
        ACC_OpeningBalanceDetail,
        std_student,
        StudentForm,
        FiscalYear,
        ACC_FiscalYear,
        Receipt,
        ServiceOutline,
        FollowUp,
        Invoice,
        Services,
        Appointment,
        customer,
        RCV_Receipt,
     
        RCV_Customer,
        RCV_Invoice,
        INQ_FollowUp,
        INQ_Inquiry,
        INQ_ServiceOutline,
        inq_serviceoutline,
        inq_Services,
        CTL_AdditionalParameter,
        ctl_additionalparameter,
        NOT_Notification_Template,
        NOT_Notificationtemplate,
        INQ_ServiceCharges,
        INQ_ServiceCompaign,
    }
}
